# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'CD: Deploy build artifact to composite target'
run-name: 'Deploy to composite target: "${{github.event.client_payload.commit_header}}" ➡️ ${{github.event.client_payload.target_description}}'

on:
  repository_dispatch:
    types: [build-completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-outputs.outputs.environment }}
      version: ${{ steps.set-outputs.outputs.version }}
      
    name: ${{ github.event.client_payload.deploy_env }} - Deploy ${{ github.event.client_payload.short_hash }} from ${{ github.event.client_payload.branch }}
    steps:
      # Mostly for the sake of the deploy action, which assumes a git directory is present
      - name: Checkout
        uses: actions/checkout@v5
        with:
          filter: 'blob:none' # only retrieve metadata

      # Get environment, version, etc from dispatch payload
      - name: Fetch inputs from dispatch
        run: |
          echo "DEPLOY_ENV=${{ github.event.client_payload.deploy_env }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

          echo "TARGET_REPO=${{ github.event.client_payload.target_repo }}" >> $GITHUB_ENV
          echo "TARGET_PATH=${{ github.event.client_payload.target_path }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.client_payload.pr_number }}" >> $GITHUB_ENV

          echo "environment=${{ github.event.client_payload.deploy_env }}" >> $GITHUB_OUTPUT
          echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT

      - name: Echo inputs from dispatch
        run: |
          echo "Deploying commit ${{ github.event.client_payload.commit_hash }}"
          echo "Commit header: ${{ github.event.client_payload.commit_header }}"
          echo "Branch: ${{ github.event.client_payload.branch }}"
          echo "Deploying version: ${{ github.event.client_payload.version }}"
          echo "Environment: ${{ github.event.client_payload.deploy_env }}"
          echo "Deploy target: /${{ env.TARGET_PATH }} @ ${{ env.TARGET_REPO }}"
          
      # https://github.com/marketplace/actions/download-workflow-artifact
      - name: Download a Build Artifact
        uses: dawidd6/action-download-artifact@v2.26.1
        with:
          workflow: ci_pipeline.yml
          name: build-${{ env.DEPLOY_ENV }}${{ env.PR_NUMBER }}
          path: ./build/

      - name: Deploy to composite repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          ssh-key: ${{ secrets.SSH_DEPLOY_HUB_SUBDOMAIN }}
          repository-name: ${{ env.TARGET_REPO }}
          target-folder: ${{ env.TARGET_PATH }}
          clean: $DEPLOY_ENV == 'production' # Set to false if deploying to a composite repository's root!
          git-config-name: "github-actions"
          git-config-email: "github-actions@github.com"

      - name: Post-deployment notification
        run: |
          if [[ "${{ env.DEPLOY_ENV }}" == "production" ]]; then
            echo "### Production build artifact uploaded! 🚀" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ env.DEPLOY_ENV }}" == "pr-staging" ]]; then
            echo "### Staging build artifact uploaded for PR #${{ env.PR_NUMBER }}! 🚀" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Staging build artifact uploaded! 🚀" >> $GITHUB_STEP_SUMMARY
            echo "To deploy to production, manually trigger the 'CI: Trigger staging deployment from main' workflow." >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: $DEPLOY_ENV" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deploy Target**: ${{ env.TARGET_PATH }} @ ${{ env.TARGET_REPO }}" >> $GITHUB_STEP_SUMMARY
          echo "- **URL (once live)**: https://hub.ciroh.org${{ env.BASE_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Deployment to GitHub Pages will be completed by the composite target repository, $TARGET_REPO." >> $GITHUB_STEP_SUMMARY