# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Trigger logic has been spun out into the various 'ci_trigger_*.yml' workflows.

name: 'CI: Create Build Artifact'
run-name: 'Create build artifact for ${{github.event.client_payload.type_description}}: "${{github.event.client_payload.commit_header}}"'

on:
  repository_dispatch:
    types: [create-build]
      
concurrency:
  group: "uploads-build-artifact"
  cancel-in-progress: ${{ github.event.client_payload.deploy_env == 'production' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Extract payload inputs
      run: |
        echo "DEPLOY_ENV=${{ github.event.client_payload.deploy_env }}" >> $GITHUB_ENV
        echo "TARGET_REPO=${{ github.event.client_payload.target_repo }}" >> $GITHUB_ENV
        echo "TARGET_PATH=${{ github.event.client_payload.target_path }}" >> $GITHUB_ENV
        echo "COMMIT_HEADER=${{ github.event.client_payload.commit_header }}" >> $GITHUB_ENV
        echo "PR_NUMBER=${{ github.event.client_payload.pr_number }}" >> $GITHUB_ENV
      # PR_NUMBER can and should be left empty for non-PR builds
      
    - name: Validate payload inputs
      run: |
        if ![["$DEPLOY_ENV" = "production"] || ["$DEPLOY_ENV" = "staging"] || ["$DEPLOY_ENV" = "pr-staging"]]; then
          echo "Invalid DEPLOY_ENV value '$DEPLOY_ENV'. Expected 'production', 'staging', or 'pr-staging'."
          exit 1
        fi
    
    - name: Generate base URL
      run: |
        if ${{ env.TARGET_PATH != '.' }}; then
          echo "BASE_URL=/${{ env.TARGET_PATH }}" >> $GITHUB_ENV
        else
          echo "BASE_URL=/" >> $GITHUB_ENV
        fi

    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.client_payload.source_ref }}
        repository: ${{ github.event.client_payload.source_repo }}
       
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Generate version
      id: version
      run: |
        version=$(date +'%Y%m%d-%H%M%S')
        echo "VERSION=${version}" >> $GITHUB_OUTPUT
        echo "VERSION=${version}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        npm ci
    # If you're here because of an error about dependencies:
    # that issue is most likely because of the `package-lock.json`.
    # Delete `node_modules` and `package-lock.json` on your
    # development environment, then run `npm i` to generate
    # a fresh lock file.
    # See also: https://github.com/npm/cli/issues/4828

    - name: Configure baseUrl
      run: |
        # Create a backup of the original config
        cp docusaurus.config.js docusaurus.config.js.bak
        
        # Use sed to replace the baseUrl value
        echo "Setting baseUrl to path '$BASE_URL'"
        sed -i 's|baseUrl: '\''\/local\/'\''|baseUrl: '\''${{ env.BASE_URL }}'\''|g' docusaurus.config.js
        sed -i 's|baseUrl: "\/local\/"|baseUrl: '\''${{ env.BASE_URL }}'\''|g' docusaurus.config.js
        sed -i 's|baseUrl = '\''\/local\/'\''|baseUrl = '\''${{ env.BASE_URL }}'\''|g' docusaurus.config.js
        sed -i 's|baseUrl = "\/local\/"|baseUrl = '\''${{ env.BASE_URL }}'\''|g' docusaurus.config.js
        
        # Show the changed config
        config_out="$(cat docusaurus.config.js | head -n 10)"
        echo "Modified docusaurus.config.js (first 10 lines):"
        echo "${config_out}"

    # Build the site
    - name: Build website
      run: npm run build
      env:
          ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
          ZOTERO_CIROH_GROUP_ID: ${{ secrets.ZOTERO_CIROH_GROUP_ID }}
          ZOTERO_STAGING_API_KEY: ${{ secrets.ZOTERO_STAGING_API_KEY }}
          ZOTERO_CIROH_STAGING_GROUP_ID: ${{ secrets.ZOTERO_CIROH_STAGING_GROUP_ID }}
          CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_REGION: ${{ secrets.S3_REGION }}
          HS_CLIENT_ID: ${{ secrets.HS_CLIENT_ID }}
          HS_FEATURED_APPS_COLLECTION_ID: ${{ vars.HS_FEATURED_APPS_COLLECTION_ID }}
          HS_FEATURED_DATASETS_COLLECTION_ID: ${{ vars.HS_FEATURED_DATASETS_COLLECTION_ID }}
          HS_FEATURED_COURSES_COLLECTION_ID: ${{ vars.HS_FEATURED_COURSES_COLLECTION_ID }}
          HS_FEATURED_PRESENTATIONS_COLLECTION_ID: ${{ vars.HS_FEATURED_PRESENTATIONS_COLLECTION_ID }}
          HS_FEATURED_NOTEBOOKS_COLLECTION_ID: ${{ vars.HS_FEATURED_NOTEBOOKS_COLLECTION_ID }}
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: build-${{ env.DEPLOY_ENV }}${{ env.PR_NUMBER }}
        # A file, directory or wildcard pattern that describes what to upload
        path: build/

    - name: Create release
      if: ${{ env.DEPLOY_ENV == 'production' }}
      uses: actions/create-release@v1
      id: create_release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: v${{env.VERSION}}
          release_name: Release v${{env.VERSION}}
          draft: false
          prerelease: false

    # Get short SHA first
    - name: Get short SHA
      id: short-sha
      run: echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    
    # Trigger CD workflow using repository dispatch          
    - name: Trigger deployment
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: build-completed
        client-payload: '{"deploy_env": "${{ env.DEPLOY_ENV }}", "version": "${{ env.VERSION }}", "target_repo": "${{ env.TARGET_REPO }}", "target_path": "${{ env.TARGET_PATH }}", "short_hash": "${{ steps.short-sha.outputs.SHORT_SHA }}", "commit_hash": "${{ github.sha }}", "commit_header": "${{ env.COMMIT_HEADER }}", "branch": "${{ github.ref_name }}", "pr_number": "${{ env.PR_NUMBER }}", "target_description": "/${{ env.TARGET_PATH }} @ ${{ env.TARGET_REPO }}"}'