# Triggers a CI/CD deployment from the main branch to staging.

name: 'CI: Trigger deployment from PR'
run-name: 'Trigger PR deployment from PR #${{ github.event.number }}'

on:
  pull_request_target:
    types: [labeled, reopened, synchronize]

env:
  STAGING_REPO: ${{ vars.COMPOSITE_TARGET_REPO }}
  STAGING_PATH: staging/

jobs:
#  debug-show-condition: 
#    runs-on: ubuntu-latest
#    steps:
#    - name: 'Echo conditions'
#      run: |
#        echo "Has flag: ${{ contains(github.event.pull_request.labels.*.name, 'preview on staging') }}"
#        echo "Is a labelling action: ${{ github.event.action == 'labeled' }}"
#        echo "Is applying flag: ${{ github.event.label.name == 'preview on staging' }}"

  trigger-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview on staging') && ( github.event.action != 'labeled' || github.event.label.name == 'preview on staging' ) }}
    runs-on: ubuntu-latest
    steps:
    - name: Set deployment target
      run: |
        echo "DEPLOY_ENV=pr-staging" >> $GITHUB_ENV
        echo "TARGET_REPO=$STAGING_REPO" >> $GITHUB_ENV
        echo "TARGET_PATH=${{ env.STAGING_PATH }}${{ github.event.number }}/" >> $GITHUB_ENV
        echo "Deploying to $STAGING_REPO as STAGING at path $STAGING_PATH${{ github.event.number }}/"
        echo "SOURCE_REPO=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_ENV
        echo "SOURCE_REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

    # Checkout to fetch commit header
    - name: Checkout
      uses: actions/checkout@v5
      with:
        repository: ${{ env.SOURCE_REPO }}
        ref: ${{ env.SOURCE_REF }}
        filter: 'blob:none' # only retrieve metadata
      
    - name: Fetch commit header
      run: |
        header="$(git log -1 --pretty=%B | head -n 1)"
        echo "COMMIT_HEADER=${header}" >> $GITHUB_ENV
      # Credit to the solution at https://github.com/orgs/community/discussions/106392

    - name: 'Send repository dispatch'
      uses: peter-evans/repository-dispatch@v4
      with:
        event-type: create-build
        client-payload: '{"deploy_env": "${{ env.DEPLOY_ENV }}", "source_ref": "${{ env.SOURCE_REF }}", "source_repo": "${{ env.SOURCE_REPO }}", "target_repo": "${{ env.TARGET_REPO }}", "target_path": "${{ env.TARGET_PATH }}", "commit_header": "${{ env.COMMIT_HEADER }}", "pr_number": "${{ github.event.number }}", "type_description": "PR #${{ github.event.number }} staging"}'

  notify:
    if: ${{ vars.SILENCE_COMPOSITE_PR_MESSAGE != 'true' && github.event.action == 'labeled' && github.event.label.name == 'preview on staging' }}
    runs-on: ubuntu-latest
    needs: trigger-build
    steps:
    - name: Comment PR with staging link
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          **Staging Preview:**
          🚀 https://hub.ciroh.org/staging/${{ github.event.number }}
          _Will be live within ~10 minutes of this message_
            
          _Built from commit ${{ github.sha }}_
